backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "public/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Project Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["Residential", "Commercial", "Industrial"] }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Project Image", widget: "image" }
